projects:
  app:
    schemaPath: "src/schema.graphql"
    extensions:
      endpoints:
        default: ${env:PRISMA_API_ENDPOINT}:${env:PRISMA_PORT}
  prisma:
    schemaPath: "src/generated/prisma.graphql"
    extensions:
      prisma: prisma/prisma.yml
