version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.28
    restart: always
    ports:
    - ${PRISMA_PORT}:${PRISMA_PORT}
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        port: ${PRISMA_PORT}
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: ${MYSQL_PASSWORD_PRISMA}
            database: ${MYSQL_DATABASE_PRISMA}
            migrations: true
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD_PRISMA}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_PRISMA}
      MYSQL_USER: ${MYSQL_USER_PRISMA}
      MYSQL_DATABASE: ${MYSQL_DATABASE_PRISMA}
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: